name: Sync Upstream

on:
  workflow_dispatch:
  schedule: [ cron: '0 0 * * *' ]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          upstream_repo: https://github.com/toptal/haste-server.git
          upstream_branch: master
          downstream_branch: master
          token: ${{ secrets.GITHUB_TOKEN }}
    
